openapi: 3.0.0
info:
  title: Pokhiliuk Ecommerce API
  description: Artem Pokhiliuk's training progect 
  version: 1.0.0
servers:
  - url: https://$$$$$$$$$$-production.up.railway.app/api/v1
    description: Main (production) server
  - url: localhost:8000/api/v1
    description: Internal staging server for testing
paths:
  /listing-categories/tree:
    get:
      summary: Returns a tree of categories (nested structure).
      responses:
        '200':    # status code
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ResponseObject'
  /category:
    post:
      summary: Adds a new category. Requires authorization
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses: 
        '201':
          description: New category has been added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
        '401':
          description: Access token is missing or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
        '400':
          description: Bad request. Category has not been added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseObject'
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
  schemas:
    ResponseObject:
      type: object
      properties:
        success:
          type: boolean
        data:
          oneOf:
            - type: array
              items:
                $ref: '#/components/schemas/Category'
            - type: object
              oneOf:
                - $ref: '#/components/schemas/Category'
                - $ref: '#/components/schemas/Error'
        message:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 10
        name:
          type: string
          example: High heels
        parent_id:
          type: integer
          nullable: true
        grandparent_id:
          type: integer
          nullable: true
        children:
          type: array
          items:
            $ref: '#/components/schemas/Category'
      required:
        - name
    Error:
      type: object
      properties:
        error:
          type: string
          example: Bad request
      required:
        - error