openapi: 3.0.0
info:
  title: Pokhiliuk Ecommerce API
  description: Artem Pokhiliuk's training progect 
  version: 1.0.0
servers:
  - url: https://$$$$$$$$$$-production.up.railway.app/api/v1
    description: Main (production) server
  - url: localhost:8000/api/v1
    description: Internal staging server for testing
paths:
  /register:
    post:
      summary: Sign up for this application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Successfull registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/APIToken'
        '400':
          description: Vaildation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/ValidationError'
  /login:
    post:
      summary: Log in to this application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successfull authentithication
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/APIToken'
        '401':
          description: Invalid authentication credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/ValidationError'
  /products:
    get:
      summary: Returns a list of products in the database.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
  /listing-categories/tree:
    get:
      summary: Returns a tree of categories (nested structure).
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
  /category:
    post:
      summary: Adds a new category. Requires authorization
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses: 
        '201':
          description: New category has been added
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Category'
        '401':
          description: Access token is missing or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request. Category has not been added
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
  schemas:
    ResponseObject:
      type: object
      properties:
        success:
          type: boolean
        data:
          oneOf:
            - type: array
              items:
                $ref: '#/components/schemas/Category'
            - type: object
              anyOf:
                - $ref: '#/components/schemas/APIToken'
                - $ref: '#/components/schemas/Error'
                - $ref: '#/components/schemas/ValidationError'
                - $ref: '#/components/schemas/Category'
        message:
          type: string
    Product:
      required: [id, name, slug, description, category_id, price, weight, length, width]
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        description:
          type: string
          nullable: true
        category_id:
          type: integer
        price:
          type: number
        weight:
          type: number
          nullable: true
        length:
          type: number
          nullable: true
        width:
          type: number
          nullable: true
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        parent_id:
          type: integer
          nullable: true
        grandparent_id:
          type: integer
          nullable: true
        children:
          type: array
          items:
            $ref: '#/components/schemas/Category'
      required:
        - name
    Error:
      type: object
      properties:
        error:
          type: string
      required:
        - error
    ValidationError:
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        c_password:
          type: array
          items:
            type: string
    RegisterRequest:
      type: object
      required: [name, email, password, c_password]
      properties:
        name:
          type: string
          minLength: 1
        email:
          type: string
        password:
          type: string
        c_password:
          type: string
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
    APIToken:
      type: object
      required: [token, name]
      properties:
        token:
          type: string
        name:
          type: string